version: '3.8'

# Komplexáci Gaming Clan Website
# Uses host networking for better performance and direct access to host network
services:
  komplexaci-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: komplexaci:latest
    container_name: komplexaci-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
